name: Input and Continue Workflow
on:
  push:
    branches:
      - main

jobs:
  run-based-on-input:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        continue_workflow: [true, false]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some initial setup steps
        run: |
          # Add your initial setup steps here
          echo "Running initial setup..."

      - name: Check if workflow should continue
        if: ${{ matrix.continue_workflow == 'true' }}
        run: |
          # Perform any checks or actions based on the input value
          echo "The input value is true. Continuing the workflow..."

      - name: Stop workflow if input is false
        if: ${{ matrix.continue_workflow != 'true' }}
        run: |
          echo "The input value is false. Stopping the workflow..."
          exit 1

      - name: Continue with additional steps
        if: ${{ matrix.continue_workflow == 'true' }}
        run: |
          # Perform additional steps that should only run if input is true
          echo "Continuing with additional steps..."
